import { Component } from '@angular/core';

@Component({
  selector: 'app-bodies',
  templateUrl: './bodies.component.html',
  styleUrls: ['./bodies.component.css']
})
export class BodiesComponent {

isDisplay: boolean = false;
bodies: any [] = [
  {name:"Trend 1", subtitle:"Breakout moment of artificial intelligence (AI) in manufacturing.", details:"AI is now part of everyday life, driven by the emergence of a device ecosystem including Alexa, Siri, and Google Assistant. In 2020, emotion recognition and computer vision will scale and AI will have a breakout moment in manufacturing.U.S. startups Vicarious, Kindred, and Osaro stand out in using AI technologies for manufacturing. Kindred’s technology is used to automate part of distribution for apparel brands such as GAP. Vicarious is attracting investment from Mark Zuckerberg, Jeff Bezos, and Elon Musk."}, 
  {name:"Trend 2", subtitle:"Practical deployment of Internet of Things (IoT).",details:"IoT is hot but there are not as many mainstream applications today as some predicted. We anticipate that with 5G, the number of connected devices and mainstream IoT applications will reach scale. Amazon recently launched Amazon Go, a system that uses IoT and machine vision technologies to enable consumers to shop without manual check out. Environments will use more sensors and vision technologies, enabling more scalable IoT solutions. Startups Standard Cognition (U.S.), Accel Robotics (U.S.), Trigo (Israel), Grabango (U.S.), and AiFi (U.S.) provide similar services as Amazon Go."}, 
  {name:"Trend 3", subtitle:"Increased demand for edge computing processing power.", details:"2020 will see the need for higher performance from edge computing hardware since better sensors and larger AI models now enable a host of new applications. There is a growing need to infer more data and then make decisions without sending data to the cloud.Chip startups SambaNova (U.S.), Graphcore (U.K.), Cerebras (U.S.), Wave Computing (U.S.), and Syntiant (U.S.) have developed architectures to handle increased demand. High-performing AI chips, known as neuromorphic or brain chips, mimic the structure of ​​the brain and process top AI algorithms."}, 
  {name:"Trend 4", subtitle:"Commercialization of quantum computing usage in mass scale.", details:"We expect 2020 to begin the quantum computing era. As data increases, quantum computing will target the biggest problems in industry, such as health care and energy. In 2020, the ability to handle big data will be required for cancer treatment, nuclear energy control, and DNA analysis. Corporations IBM, Google, Intel, Microsoft, and Alibaba have moved into quantum computing. Startups Rigetti (U.S.), D-Wave Systems (Canada), and QC Ware (U.S.) are disrupting quantum computing. The technology will grow as it becomes easier to use with platforms such as Amazon Web Services by mid-2020."},
  {name:"Trend 5", subtitle:"Evolution of aerospace technologies.", details:"Mankind will begin its return to space in 2020, largely driven by the private sector. Since the Cold War, technological advances have slowed. Notable companies now making aerospace advancements include SpaceX and Blue Origin. SpaceX is developing the rocket Starship, which will reuse the entire vehicle body. Starship may shorten intercontinental trips to 20-30 minutes via space. In China, the government and private enterprises (example: LinkSpace) are making progress in space."}, 
  {name:"Trend 6", subtitle:"New era of the internet — deployment of 5G and Starlink broadband internet technology.", details:"5G competition between the U.S. and China is entering the main stage in 2020. There will be a new competition about who can propel 5G faster into mass consumer use. Another hot topic is the Starlink Broadband business planned by SpaceX. Until 2020, as many as 2,500 satellites will be launched. This marks a new era of broadband Internet for some users in North America. Starlink’s broadband Internet system will grow with 12,000 satellites through 2023, followed by the addition of 30,000 satellites. SpaceX will provide higher speed Internet starting in 2020."}, 
  {name:"Trend 7", subtitle:"Evolution of health care — predictions at the genome level.", details:"Under the theme of prevention, digital health care has seen much innovation. In the U.S., startups 23andMe and Color lead in genome analysis, while Genesis Healthcare stands out in Japan and Genoplan in Korea. These companies use genomic analysis to learn of diseases and provide prevention methods. The evolution of AI will improve the quality of treatment. In 2020, many medical images taken using MRI, CT scans, and X-rays will be diagnosed using AI. Startups Enlitic and Zebra Medical Vision stand out as leaders."}, 
  {name:"Trend 8", subtitle:"Evolution in Agriculture – technology to Grow Crops Efficiently.", details:"In agriculture, companies that offer products using computer vision, AI, and big data stand out. In 2020, it will become common to monitor crop growth by computer vision Ceres Imaging (U.S.), Taranis (Israel), Farmwise (U.S.). Robots, such as those by Abundant Robotics, that harvest plants and fruits will become more common. The technology for improving crop growth efficiency will also be enhanced by indoor farming companies, such as Bowery Farming (U.S.), funded by GV."},
  {name:"Trend 9", subtitle:"Evolution of autonomous driving technology.", details:"Autonomous driving is already a hot topic, although level 5 (fully autonomous) has not been realized. Some Tesla cars can be switched to autopilot mode on the highway, but this is only possible up to level 2 (driving support) or level 3 (operated by the driver in an emergency). Technology for understanding detailed road conditions by AI is evolving. Startups Prophesee (France), Perceptive Automata (U.S.), and Humanising Autonomy (U.K.) stand out as leaders. They will contribute towards achieving level 5 in 2020."},
  {name:"Trend 10", subtitle:"The U.S. and China put blockchain to practical use.", details:"As blockchain grows, payment-type venture companies and venture companies in security — such as Chainalysis, which develops money laundering countermeasure technology — are attracting attention. In 2020, major institutions will introduce blockchain to prevent large-scale information leakage and Internet fraud. IBM set up an accelerator program specializing in blockchain. China approved the introduction of blockchain in services such as ICBC (China Industrial and Commercial Bank), Alibaba Group, China Southern Airlines, etc. In 2020, blockchain will be put to practical use."},
  ];

  toggleButton() {
    this.isDisplay = !this.isDisplay;
  }

}